name: Bot
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: read
concurrency:
  group: bot
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ["1.1.22"]
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_KV_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT }}
      CLOUDFLARE_KV_NAMESPACE: ${{ secrets.CLOUDFLARE_KV_NAMESPACE }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/setup@v2
        with:
          runtime: bun@${{ matrix.bun }}
          cache: true
          install: false
      - run: pnpm install --frozen-lockfile --prod
      - name: Restore cookies
        run: |
          set -euo pipefail

          curl "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$CLOUDFLARE_KV_NAMESPACE/values/cookies" \
            --fail --silent --show-error \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -o cookies.encrypted || : > cookies.encrypted

          openssl enc -d -des3 -base64 -A -pbkdf2 -pass env:ENCRYPTION_KEY \
            -in cookies.encrypted -out cookies.json 2>/dev/null || echo '{}' > cookies.json

          sha256sum < cookies.json | cut -d " " -f 1 > cookies.checksum
      - name: Run bot
        timeout-minutes: 2
        env:
          VRCHAT_EMAIL: ${{ secrets.VRCHAT_EMAIL }}
          VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRCHAT_TOTP_SECRET: ${{ secrets.VRCHAT_TOTP_SECRET }}
          MEDIAWIKI_USERNAME: ${{ secrets.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
          BYPASS_TOKEN: ${{ secrets.BYPASS_TOKEN }}
        run: bun src/index.ts
      - name: Save cookies
        run: |
          set -euo pipefail

          if [ "$(sha256sum < cookies.json | cut -d " " -f 1)" = "$(cat cookies.checksum)" ]; then
            exit 0
          fi

          openssl enc -e -des3 -base64 -A -pbkdf2 -pass env:ENCRYPTION_KEY \
            -in cookies.json -out cookies.encrypted

          curl "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$CLOUDFLARE_KV_NAMESPACE/values/cookies" \
            --fail --silent --show-error \
            -X PUT \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -F "value=<cookies.encrypted" \
            -o /dev/null
